### ISSUE TITLE
Kanban setup

### ISSUE THREAD

**Issue by inspecta** [inspecta/RoR-Food-Recipes#12]
In this milestone,
- We are a group of 2 members
- We created an empty repository
- Setup the Kanban board with some columns
- Created tasks in the Kanban board based on the project requirements
- Each task was created on a separate card with a title, description, and number of points
- We assigned the tasks equally amongst ourselves
**Here's a link to our RoR Kanban Project** [RoR-Food-Recipes](https://github.com/users/inspecta/projects/4)

**Comment by Ghiftee** [comment]
Hi team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have the link to your project. Kindly include the link to your knaban board in your issue.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by Munsa1** [comment]
Hi @inspecta @Joel-100 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Good communication with the reviewer :heavy_check_mark: 
Equal distribution of workloads :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by inspecta** [comment]
Thanks @Munsa1
